//
// Created by bartosz on 3/31/22.
//

#ifndef SMART_LIGHT_MAIN_H
#define SMART_LIGHT_MAIN_H

#define LED_RING_OUT_PIN GPIO_NUM_32
#define LED_RING_LED_COUNT 12

#define LED_YELLOW_PIN GPIO_NUM_27
#define LED_GREEN_PIN GPIO_NUM_26
#define LED_RED_PIN GPIO_NUM_25
//#define LED_YELLOW_PIN GPIO_NUM_18
//#define LED_GREEN_PIN GPIO_NUM_19
//#define LED_RED_PIN GPIO_NUM_17

#endif //SMART_LIGHT_MAIN_H
